FROM denoland/deno:alpine

WORKDIR /app

COPY package*.json /app/

RUN deno install

COPY . /app/

EXPOSE 8080

CMD ["deno", "run", "--allow-all", "--unstable-sloppy-imports", "src/index.ts"]