FROM denoland/deno:alpine

WORKDIR /app

COPY package*.json /app/ 
COPY deno.lock /app/

RUN deno install

COPY . /app/

EXPOSE 8000

CMD ["deno", "run", "--allow-all", "--unstable-sloppy-imports", "src/index.ts"]